sudo: required
language: go

before_install:
  - travis_retry curl -sf https://up.apex.sh/install | sudo sh
  - sudo up upgrade

install:
  - go get -t ./...
  - sudo apt-get install jq -y

script:
  - true # avoid default make command

matrix:
  include:
    - env: DEPLOY=dev
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script: make
        on:
          branch: master
    - env: DEPLOY=demo
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script: AWS_ACCESS_KEY_ID=$AWS_915001051872_ID AWS_SECRET_ACCESS_KEY=$AWS_915001051872_SECRET make demo
        on:
          branch: master
    - env: DEPLOY=prod
      if: tag IS present
      deploy:
        provider: script
        skip_cleanup: true
        script: AWS_ACCESS_KEY_ID=$AWS_192458993663_ID AWS_SECRET_ACCESS_KEY=$AWS_192458993663_SECRET make prod
        on:
          tags: true
